### ISSUE TITLE
low quality and resolution problem

### ISSUE THREAD

**Issue by halilgulez** [enzogostadebolo/google-images-downloader#1]
hey man,
can we increase the png resolution and quality?

**Comment by enzoribeirodev** [comment]
Hey
I have just commited an another version of my program, this time, i've used requests-html. Unlike the other version, this one manages to download the images in the best possible quality. It's still a little slow, due to the many requests and renders needed. You can change the sleep values if you want. I tried to integrate async but I had memory overload problems, which were not resolved even using the multiprocessing pool.
